{{- if .Values.ingress.enabled -}}
{{- $fullName := include "nginx.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if and .Values.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.ingress.annotations "kubernetes.io/ingress.class" .Values.ingress.className}}
  {{- end }}
{{- end }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "nginx.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  tls:
  - hosts:
    - {{ .Values.base_domain }}
    {{- range .Values.ingress.tls }}    
    secretName: {{ .secretName }}-{{ $fullName }}
    {{- end }}
    rules:
      - host: {{ .Values.base_domain }}
        {{- range .Values.ingress.hosts }}
        http:
          paths:
            {{- range .paths }}
            - path: {{ .path }}
              backend:
                {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
                service:
                  name: {{ $fullName }}
                  port:
                    number: {{ $svcPort }}
                {{- else }}
                serviceName: {{ $fullName }}
                servicePort: {{ $svcPort }}
                {{- end }}
            {{- end }}
        {{- end }}
{{- end }}